= Entity Framework Core API Reference
:description: The API reference for the Couchbase EF Core Provider.


[abstract]
{description}

== Entity Framework Core API Reference

The Couchbase EF Core Provider is an extension of the Entity Framework Core API.
The API Reference is largely consistent with the https://learn.microsoft.com/en-us/ef/[Entity Framework Core API Reference], with the addition of Couchbase-specific features.
These features are covered in the following sections:

* xref:entity-framework-core-configuration.adoc[Couchbase EF Core Configuration]
* xref:entity-framework-core-modeling.adoc[Couchbase EF Core Modeling]
* xref:entity-framework-core-crud-data.adoc[Couchbase EF Core CRUD]
* xref:entity-framework-core-queries.adoc[Couchbase EF Core Querying]

We suggest you start with the xref:entity-framework-core-configuration.adoc[Couchbase EF Core Configuration] section,
and then move on to the xref:entity-framework-core-modeling.adoc[Couchbase EF Core Modeling] section.
The xref:entity-framework-core-queries.adoc[Couchbase EF Core Querying] section is a good place to learn about the Couchbase-specific querying features.
The xref:entity-framework-core-crud-data.adoc[Couchbase EF Core CRUD] section is a good place to learn about the Couchbase-specific CRUD features.
Features and subjects not covered in this documentation can likely be found in the https://learn.microsoft.com/en-us/ef/[EF Core documentation].
