= Saving Data
:paga-toclevels: 2
// :nav-title: Saving Data
:description: Entity Framework Core (EF Core) supports two fundamental approaches for saving data to the database.



[abstract]
{description}

While querying allows you to read data from the database, saving data means adding new entities to the database, removing entities, or modifying the properties of existing entities in some way. 
Entity Framework Core (EF Core) supports two fundamental approaches for saving data to the database.


== Approach 1: Change Tracking and SaveChangesAsync

In many scenarios, your program needs to query some data from the database, perform some modification on it, and save those modifications back;
this is sometimes referred to as a https://en.wikipedia.org/wiki/Unit_of_work["Unit of Work"].
For example, let's assume that you have a set of Blogs, and you'd like to change the Url property of one of them.

[NOTE]
Like any EF Core Provider `DbContext`, lifetime, configuration, and initialization https://learn.microsoft.com/en-us/ef/core/dbcontext-configuration/[best practices] should be used with the `DbContext`.
Always call https://learn.microsoft.com/en-us/ef/core/dbcontext-configuration/#the-dbcontext-lifetime[Dispose()] when done using the `DbContext`.

In EF, this is typically done as follows:
[source,csharp]
----
using (var context = new BloggingContext())
{
    var blog = await context.Blogs.SingleAsync(b => b.Url == "http://example.com");
    blog.Url = "http://example.com/blog";
    await context.SaveChangesAsync();
}
----

The code above performs the following steps:

. It uses a regular LINQ query to load an entity from the database and adds them to the internal change tracker.
. The retrieved entities `Url` property is modified.
. Finally, `DbContext.SaveChangesAsync()` is called and the entity's modified properties are persisted to the database.

[IMPORTANT]
This provider is asynchronous-only -- synchronous APIs like `SaveChanges()`/`.Single()` throw
`NotSupportedException` in Release builds. Use the `Async` variants throughout, as in the examples
on this page. See xref:entity-framework-core-limitations.adoc#only-async-queries-supported[Limitations].


== Approach 2: Bulk Update with ExecuteUpdateAsync and ExecuteDeleteAsync

`SaveChangesAsync` is a powerful model for persisting changes to the database, but has some limitations.
The main limitation is that each entity must be tracked and when `SaveChangesAsync` is called, each modified or added entity will be persisted to the database.
This can be inefficient -- a more efficient way of doing this is via an `UPDATE` or `DELETE` command.

The following is an example of a bulk operation using `ExecuteDeleteAsync`:

[source,csharp]
----
await context.Blogs.Where(b => b.Rating < 3).ExecuteDeleteAsync();
----

An example of `ExecuteUpdateAsync` is as follows:

[source,csharp]
----
 await context.Airlines
    .Where(a => a.Id > 665 && a.Id < 668)
    .ExecuteUpdateAsync(setters =>
        setters.SetProperty(a => a.Country, "Lilliput"));
----

More information on the differences between SaveChanges, `ExecuteUpdate`, and `ExecuteDelete` can be found in the https://learn.microsoft.com/en-us/ef/core/saving/[main EF Core documentation].


== Adding Data

Use the `DbSet<TEntity>.Add` method to add new instances of your entity classes.
The data will be inserted into the database when you call `DbContext.SaveChangesAsync()`:

[source,csharp]
----
using (var context = new BloggingContext())
{
    var blog = new Blog { Url = "http://example.com" };
    context.Blogs.Add(blog);
    await context.SaveChangesAsync();
}
----


== Updating Data

EF automatically detects changes made to an existing entity that is tracked by the context.
This includes entities that you load/query from the database, and entities that were previously added and saved to the database.

Simply modify the values assigned to properties and then call `SaveChangesAsync`:

[source,csharp]
----
using (var context = new BloggingContext())
{
    var blog = await context.Blogs.SingleAsync(b => b.Url == "http://example.com");
    blog.Url = "http://example.com/blog";
    await context.SaveChangesAsync();
}
----


== Deleting Data

Similar to adding and updating data, deleting means using `DbSet<TEntity>.Remove` to delete entity instances from the database:

[source,csharp]
----
using (var context = new BloggingContext())
{
    var blog = await context.Blogs.SingleAsync(b => b.Url == "http://example.com/blog");
    context.Blogs.Remove(blog);
    await context.SaveChangesAsync();
}
----

If the entity exists in the database, it will be removed from the database, otherwise it will be removed from the current context when SaveChangesAsync is called.


== Combining Operations in a single SaveChangesAsync

You can combine multiple Add/Update/Remove operations into a single call to `SaveChangesAsync`:

[source,csharp]
----
using (var context = new BloggingContext())
{
    // seeding database
    context.Blogs.Add(new Blog { Url = "http://example.com/blog" });
    context.Blogs.Add(new Blog { Url = "http://example.com/another_blog" });
    await context.SaveChangesAsync();
}

using (var context = new BloggingContext())
{
    // add
    context.Blogs.Add(new Blog { Url = "http://example.com/blog_one" });
    context.Blogs.Add(new Blog { Url = "http://example.com/blog_two" });

    // update
    var firstBlog = await context.Blogs.FirstAsync();
    firstBlog.Url = "";

    // remove
    var lastBlog = await context.Blogs.OrderBy(e => e.BlogId).LastAsync();
    context.Blogs.Remove(lastBlog);

    await context.SaveChangesAsync();
}
----

[NOTE]
Single-document adds, updates, and removes made through change tracking (`Add`/`Update`/`Remove` + `SaveChangesAsync`) go through the https://docs.couchbase.com/dotnet-sdk/current/howtos/kv-operations.html[Couchbase Key/Value store] rather than {sqlpp}, since they operate on a single document by key. Bulk `ExecuteUpdateAsync`/`ExecuteDeleteAsync` (above), raw `FromSqlRaw`/`FromSql` queries, and regular LINQ queries all go through {sqlpp}.

=== Write concurrency and partial failure

When a single `SaveChangesAsync()` call has multiple independent document writes (as in the
combined example above), the provider issues them concurrently rather than one at a time, so
`SaveChangesAsync` latency doesn't scale linearly with the number of changed entities. This means
`SaveChangesAsync` is *not atomic*: if one write in the batch fails, some number of the other
writes may have already completed (a bounded, nondeterministic subset -- not necessarily a
predictable prefix), rather than none of them. If you need all-or-nothing semantics for a group of
writes, use a xref:entity-framework-core-transactions.adoc[Couchbase transaction] instead of
relying on ordering within a single `SaveChangesAsync` call.

`SaveChangesAsync` also accepts a `CancellationToken`, which is honored both when scheduling
further writes and by the in-flight KV calls themselves:

[source,csharp]
----
await context.SaveChangesAsync(cancellationToken);
----


== Saving Related Data

In addition to isolated entities, you can also make use of the relationships defined in your model.

=== Adding a Graph of New Items

If you create several new related entities, adding one of them to the context will cause the others to be added too.

In the following example, the blog and three related posts are all inserted into the database. 
The posts are found and added, because they are reachable via the Blog.Posts navigation property.

[source,csharp]
----
using (var context = new BloggingContext())
{
    var blog = new Blog
    {
        BlogId = 1,
        Url = "http://blogs.msdn.com/dotnet",
        Posts =
        [
            new() { Title = "Intro to C#", PostId = 1 },
            new() { Title = "Intro to VB.NET", PostId = 2 },
            new() { Title = "Intro to F#", PostId = 3 }
        ]
    };

    await context.Blogs.AddAsync(blog);
}
----

[TIP]
If you attempt to delete the Blog after creating it, you will get a foreign key constraint when you call `SaveChangesAsync` again, unless you provide `DeleteBehavior.Cascade` to the entity during modeling.


== Adding a related entity

If you reference a new entity from the navigation property of an entity that is already tracked by the context, the entity will be discovered and inserted into the database.

[source,csharp]
----
using (var context = new BloggingContext())
{
    var blog = await context.Blogs.FirstAsync();
    blog.Posts = await context.Posts.Where(x => x.BlogId == blog.BlogId).ToListAsync();
    var post = new Post { Title = "Intro to EF Core", PostId = 4};

    blog.Posts.Add(post);
    await context.SaveChangesAsync();
}
----

Eager loading via `Include`/`ThenInclude` is supported, including chained `ThenInclude`, `AutoInclude`,
filtered includes, and includes on many-to-many skip navigations -- see
xref:entity-framework-core-modeling.adoc#eager-loading[Modeling] for the full set of examples. For
instance, to load a blog with both its posts and its owner in one query:

[source,csharp]
----
var blogs = await context.Blogs
    .Include(b => b.Posts)
    .Include(b => b.Owner)
    .ToListAsync();
----


== Changing relationships

If you change the navigation property of an entity, the corresponding changes will be made to the foreign key column in the database.

[source,csharp]
----
using (var context = new BloggingContext())
{
    var blog = new Blog { Url = "http://blogs.msdn.com/visualstudio", BlogId = 2};
    var post = await context.Posts.FirstAsync();

    post.Blog = blog;
    await context.SaveChangesAsync();
}
----


== Removing relationships

You can remove a relationship by setting a reference navigation to null, or removing the related entity from a collection navigation.

Removing a relationship can have side effects on the dependent entity, according to the https://learn.microsoft.com/en-us/ef/core/saving/cascade-delete[cascade delete] behavior configured in the relationship.

[source,csharp]
----
using (var context = new BloggingContext())
{
    var blog = await context.Blogs.FirstAsync();
    blog.Posts = await context.Posts.Where(x => x.BlogId == blog.BlogId).ToListAsync();
    var post = blog.Posts.First();

    blog.Posts.Remove(post);
    await context.SaveChangesAsync();
}
----
